config/routes.rb
Rails.application.routes.draw do
  resources :films
  get 'main/index'
  get 'main/about'
  get '/search', to: 'search#index'
  get '/import/:id', to: 'films#import'

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  validate :rating_in_range

  def rating_in_range
    if rating.present? and (rating < 0 or rating > 5)
      errors.add(:rating, 'Je hebt een verkeerd aantal Jodensterren opgegeven.')
    end
  end

  def self.find_by_filter(params)
    @gezien = params[:gezien].to_i
    @rating = params[:rating].to_i

    if @gezien == 0
      if @rating < 0
        return Film.all
      else
        return Film.where(rating: params[:rating])
      end
    else
      if @rating < 0
        return Film.where(gezien: params[:gezien].to_i == 1)
      else
        return Film.where(rating: params[:rating], gezien: params[:gezien].to_i == 1)
      end
    end
  end

  def self.convert_rating(imdb_rating)
    return [0, ((imdb_rating - 1)/9 * 5).round].max
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'De film is aangemaakt.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'De film is bijgewerkt.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'De film is verwijderd.' }
      format.json { head :no_content }
    end
  end

  def import
    imdb_id = params[:id]
    movie = Imdb::Movie.new(imdb_id)

    @film = Film.new(titel: movie.title, synopsis: movie.plot_summary, gezien: false, rating: Film.convert_rating(movie.rating),
                    image: movie.poster, imdb: movie.url, trailer: movie.trailer_url)
    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'De gegevens van deze film zijn overgenomen van IMDb.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:titel, :synopsis, :gezien, :rating, :image, :imdb, :trailer, :comments)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if params.has_key?(:commit)
      @films = Film.find_by_filter(params)

      @gezien = params[:gezien]
      @rating = params[:rating]
    else
      @films = Film.all
    end
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  @@results_cache = []
  @@query = nil

  def index
    if @@query.nil? or @@query != params[:q]
      @query = params[:q]
      @results = Imdb::Search.new(@query).movies

      @@query = @query.dup

      @@results_cache.clear
      @results.each{|movie| @@results_cache << movie.dup}
    else
      @query = @@query
      @results = @@results_cache
    end

    @start = params.has_key?(:start) ? params[:start].to_i : 0
    @length = 10
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/films/_form.html.erb
<%= bootstrap_form_for(film) do |f| %>
  <% if film.errors.any? %>
    <div class="alert alert-danger">
      Er zijn fouten opgetreden tijdens het opslaan van deze film!
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :titel %>
  </div>

  <div class="field">
    <%= f.text_area :synopsis %>
  </div>

  <div class="field">
    <%= f.check_box :gezien %>
  </div>

  <div class="field">
    <%= f.text_area :comments, label: 'Opmerkingen bij deze film' %>
  </div>

  <div class="field">
    <%= f.number_field :rating, label: 'Jodensterren (op 5)' %>
  </div>

  <div class="field">
    <%= f.text_field :image, label: 'Afbeelding' %>
  </div>

  <div class="field">
    <%= f.text_field :imdb, label: 'IMDb pagina' %>
  </div>

  <div class="field">
    <%= f.text_field :trailer %>
  </div>

  <div class="actions btn-group">
    <%= f.submit 'Opslaan', class: 'btn btn-primary' %>
    <%= link_to 'Annuleren', root_path, class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/films/_list.html.erb
<div class="container">
<% @films.each_with_index do |film, index| %>
    <% if index % 3 == 0 %>
      <div class="row">
    <% end %>
          <div class="col-lg">
            <div class="card" style="width: 20rem; float: left">
              <%= link_to film do %>
                <img class="card-img-top" src="<%= film.image %>" width="100%" height="25%">
              <% end %>
              <div class="card-block">
                <h4 class="card-title"><%= film.titel %> <%= raw "&#10017;" * film.rating %></h4>
                <% if film.gezien %>
                    <p class="card-text">&#10004; We hebben deze film al gezien.</p>
                <% else %>
                    <p class="card-text">&#10008; We hebben deze film nog niet gezien!</p>
                <% end %>
                <p class="card-text"><%= truncate(film.synopsis, length: 256) %></p>
                <div class="btn-group">
                  <%= link_to "&#9991;".html_safe, film.trailer, class: 'btn btn-sm btn-primary', title: 'Trailer bekijken', target: '_blank' %>
                  <%= link_to "&#9998;".html_safe, edit_film_path(film), class: 'btn btn-sm btn-primary', title: 'Details bewerken' %>
                  <%= link_to "&#10006;".html_safe, film, method: :delete, data: { confirm: 'Weet je het zeker?' }, class: 'btn btn-sm btn-danger', title: 'Verwijderen' %>
                </div>
              </div>
            </div>
          </div>
    <% if index % 3 == 2 %>
        </div>
    <% end %>
<% end %>
</div>

app/views/films/edit.html.erb
<h1>Film bewerken</h1>

<%= render 'form', film: @film %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<%= render "list" %>

<br>

<%= link_to 'Film toevoegen', new_film_path %>

app/views/films/new.html.erb
<h1>Film toevoegen</h1>

<%= render 'form', film: @film %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <img src="<%= @film.image %>" style="float: left; width: 320px; height: 470px">
    <h1><%= @film.titel %> <%= raw "&#10017;" * @film.rating %></h1>
    <p>
      <%= @film.synopsis %>
    </p>
  </div>
</div>

<p style="text-align: right">
  <%= @film.gezien ? "&#10004; We hebben deze film al gezien.".html_safe : "&#10008; We hebben deze film nog niet gezien!".html_safe %>
</p>

<% if not @film.comments.blank? %>
<p>
  <strong>Opmerkingen:</strong>
  <%= @film.comments %>
</p>
<% end %>

<div class="list-group">
  <%= link_to 'IMDb pagina', @film.imdb, class: 'list-group-item list-group-item-info', target: '_blank' %>
  <%= link_to 'Trailer', @film.trailer, class: 'list-group-item list-group-item-info', target: '_blank' %>
  <%= link_to 'Details bewerken', edit_film_path(@film), class: 'list-group-item list-group-item-action' %>
  <%= link_to 'Verwijderen', @film, method: :delete, data: { confirm: 'Weet je het zeker?' }, class: 'list-group-item list-group-item-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmlijst</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Filmlijst</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Hoofdpagina', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Over deze applicatie', main_about_path, class: 'nav-link' %>
          </li>
        </ul>
        <%= form_tag("/search", method: "get", class: "form-inline my-2 my-lg-0") do %>
            <%= text_field_tag(:q, nil, placeholder: "Zoek een film op IMDb", class: "form-control mr-sm-2") %>
            <%= submit_tag("Zoeken", class: "btn btn-outline-success my-2 my-sm-0") %>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/about.html.erb
<h1>Over Filmlijst</h1>

<p>
  Ik heb deze webapplicatie gemaakt zodat Orla en ik makkelijk altijd en overal onze lijst met films kunnen bijwerken.
</p>

<h2>Films toevoegen</h2>

<p>
  Een film toevoegen kan ofwel volledig manueel ofwel met behulp van IMDb.
</p>

<p>
  Om een film manueel toe te voegen, ga je naar de hoofdpagina en klik je op de knop "Nieuwe film toevoegen".
  Je vult dan gewoon alle velden in en drukt op "Opslaan". De film komt dan in de lijst te staan.
</p>

<p>
  Om een film toe te voegen via IMDb, typ je de naam rechtsboven in het zoekveld in en klik je op "Zoeken".
  Afhankelijk van hoeveel resultaten er zijn, kan deze zoekopdracht relatief traag zijn, dus een beetje geduld is wel
  een goeie zaak. Als alles normaal verloopt, krijg je dan een lijst met titels en samenvattingen van gevonden films en
  series. Gewoon klikken op de film die je wil, is voldoende om die toe te voegen aan de lijst. Let wel op dat de
  informatie van IMDb soms onbetrouwbaar of onvolledig kan zijn, dus kijk de details zeker na. In het bijzonder
  ontbreken er vaak trailers of posters...
</p>

<h2>Films bewerken</h2>

<p>
  Eens een film is toegevoegd aan de lijst, kan je de gegevens ervan bewerken. Belangrijk zijn vooral de rating en
  of we de film al gezien hebben of niet. De applicatie gaat uit van een ratingsysteem van 0 tot 5 Jodensterren.
  (Ratings op IMDb gaan van 1 tot 10 en worden automatisch omgezet naar het Jodensysteem bij het importeren.)
</p>

app/views/main/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Filmlijst</h1>
  <p class="lead">
    Een webapplicatie om bij te houden welke films we al hebben gezien en nog zouden moeten zien.
  </p>
  <hr class="my-4">
  <p>Gemaakt met &#10084; door Jonathan voor Orla.</p>
  <div class="btn-group">
    <%= link_to 'Nieuwe film toevoegen', new_film_path, class: 'btn btn-primary' %>
  </div>
</div>

<p>Aantal films in deze lijst: <%= @films.size %></p>

<%= form_tag("/", method: "get", class: "form-inline my-2 my-lg-0") do %>
<div class="container">
  <div class="row">
    <div class="col col-lg-2">
      <%= label_tag(:gezien, "Status:") %>
    </div>
    <div class="col-12 col-md-auto">
      <%= select_tag(:gezien, options_for_select([['Allemaal', 0], ['Gezien', 1], ['Nog niet gezien', 2]], @gezien), class: 'form-control') %>
    </div>
  </div>
  <div class="row">
    <div class="col col-lg-2">
      <%= label_tag(:rating, "Rating:") %>
    </div>
    <div class="col-12 col-md-auto">
      <%= select_tag(:rating, options_for_select([['Allemaal', -1]].concat([0,1,2,3,4,5]), @rating), class: 'form-control') %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="btn-group">
        <%= submit_tag("Filteren", class: "btn btn-outline-success my-2 my-sm-0") %>
        <%= link_to "Filter verwijderen", root_path, class: "btn btn-outline-primary my-2 my-sm-0" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<%= render "films/list" %>

app/views/search/index.html.erb
<h1>Zoekresultaten voor <%= @query %></h1>

<p>Aantal resultaten: <%= @results.size %></p>
<p>Pagina <%= (@start / @length) + 1 %> van <%= (@results.size / @length).ceil %></p>

<div class="list-group">
<% @results[@start, @length].each do |movie| %>
    <%= link_to '/import/' + movie.id, class: 'list-group-item list-group-item-action flex-column align-items-start' do %>
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= movie.title %></h5>
        <small>
          <% if not movie.rating.nil? %>
              <%= raw "&#10017;" * Film.convert_rating(movie.rating) %>
          <% end %>
          &nbsp;
          <%= movie.year %>
        </small>
      </div>
      <p class="mb-1"><%= movie.plot_summary %></p>
    <% end %>
<% end %>
</div>

<div class="container">
  <% if @results.size > @length %>
  <nav>
    <ul class="pagination">
      <% if @start > 0 %>
        <li class="page-item"><%= link_to 'Begin', { controller: :search, action: :index, q: @query }, class: 'page-link' %></li>
      <% end %>
      <% if @start >= @length %>
        <li class="page-item"><%= link_to 'Vorige', { controller: :search, action: :index, q: @query, start: @start - @length }, class: 'page-link' %></li>
      <% end %>
      <% if @start <= @results.size - @length %>
        <li class="page-item"><%= link_to 'Volgende', { controller: :search, action: :index, q: @query, start: @start + @length }, class: 'page-link' %></li>
        <li class="page-item"><%= link_to 'Einde', { controller: :search, action: :index, q: @query, start: @results.size - @length }, class: 'page-link' %></li>
      <% end %>
    </ul>
  </nav>
  <% end %>
</div>